# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f8eacdefff216bb424767a56eb02816314865596014dc558ce74b89f49406e34c5d7e70550b9cba453172d8e486f6eca25267c2f8012b5f77398e96e545a6c0

test:
  secret_key_base: fd702ea0c3c963076539cea4fdc0e49a981b320cb696a8703afa3728a3b42f52a5667c2411054fb5bef69063ddb73119286cd4034ff195b7c3c936adbe35fd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
